# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e1909564512e6571a789b4f1b43f8ec65bc643e18261146408a362ea913ec58c4023c751bc70c944ef1c827b2af74ad7f52d6ce9c1a3556c0bd09d318aec0e4

test:
  secret_key_base: 4088b5f00ed884f1ef8201685e48578d6b2ec45c5946b7dda60daebdc21e170234454646f20f57fbef2b429c5ee8ac76e60d2578a6f7a2117cc2ecabe0d56266

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
